# Generated by Django 3.2.4 on 2021-08-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210803_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'М'), ('W', 'Ж'), ('N', '-')], max_length=1, null=True, verbose_name='пол'),
        ),
    ]
